version: 2

title: InContext
url: "https://incontext.app"

port: 8003

steps:

  # Ignore temporary and hidden files.
  - when: '(.*/)?(\.DS_Store|.*~|\..*)'
    then: ignore

  # Import markdown files.
  - when: '.*\.(markdown|md)'
    then: markdown
    args:
        defaultCategory: recipes
        defaultTemplate: page.html

  # Import image files.
  - when: '(.*/)?.*\.(jpg|jpeg|png|gif|tiff|heic)'
    then: image
    args:
        category: images
        titleFromFilename: False
        defaultTemplate: photo.html
        inlineTemplate: image.html

  # Copy everything else.
  - when: '.*'
    then: copy
