version: 1

title: Recipes
url: "https://recipes.jbmorley.co.uk"

port: 8003

build_steps:

  - task: "process_files"
    args:
      handlers:
        - when: '(.*/)?\.DS_Store'
          then: ignore
        - when: '(.*/)?\..*'
          then: ignore
        - when: '(.*/)?.*~'
          then: ignore
        - when: '.*\.(markdown|md)'
          then: markdown
          args:
              default_category: recipes
              default_template: page.html
        - when: 'snapshots.*\.(jpg|jpeg|png|gif|tiff|heic)'
          then: image
          args:
              category: photos
              title_from_filename: False
              default_template: photo.html
              inline_template: image.html
        - when: '.*'
          then: copy
